version: "3.8"

services:
  app:
    build:
      context: .
    container_name: trading-server
    ports:
      - "8008:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    command: >
      sh -c "
        echo '⏳ Waiting for DB...';
        sleep 5;
        uv run prisma db push --schema=./prisma &&
        uv run uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - trading-network

  postgres:
    image: pgvector/pgvector:pg17
    container_name: trading-pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trading-network

volumes:
  pg_data:

networks:
  trading-network:
    driver: bridge
    name: trading-network
