[project]
name = "trading-strategy-team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=4.3.0",
    "fastapi>=0.115.13",
    "langchain>=0.3.26",
    "langchain-experimental>=0.3.4",
    "langchain-openai>=0.3.24",
    "langgraph>=0.4.8",
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "prisma>=0.15.0",
    "pydantic[email]>=2.11.7",
    "python-dotenv>=1.1.0",
    "python-jose>=3.5.0",
    "uvicorn>=0.34.3",
    "yfinance>=0.2.63",
]
